#!/bin/bash -ex

curl $1 -o /tmp/adlists.tmp

if [ $? = 0 ]; then
        
        grep -iE '^https?:\/\/[a-z0-9.]{2,30}\.[a-z]{2,6}\b([-a-z0-9_\-\+.~#?&/=]*/)' /tmp/adlists.tmp
        if [ $? = 0 ]; then
               
                while read p; do
                    sqlite3 /etc/pihole/gravity.db "INSERT INTO "adlist" ("address","enabled","comment") VALUES ('$p','1','Automatic Insert');"
                done </tmp/adlists.tmp
                rm -rf /tmp/adlists.tmp
                #exit 0
        fi
else
echo Failed.
#exit 1
fi