#!/bin/bash -e

strAdList=/etc/pihole/adlists.list

grep -iE '^https?:\/\/[a-z0-9.]{2,30}\.[a-z]{2,6}\b([-a-z0-9_\-\+.~#?&/=]*/)' $strAdList

while read strURL; do
    sqlite3 /etc/pihole/gravity.db "INSERT INTO "adlist" ("address","enabled","comment") VALUES ('$strURL','1','Automatic Insert');";
done < $strAdList

pihole -g